import Image from "next/image";
import image1 from "../public/images/image10.jpg";

import image2 from "../public/images/image11.jpg";
import image3 from "../public/images/image12.jpg";
import { HiOutlineShoppingBag } from "react-icons/hi";

import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";

import Head from "next/head";
import Middle from "@/components/Middle";
import Link from "next/link";
const index = ({ products , addToCart}) => {
  return (
    <>
      <Head>
        <title>Ecommerce-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="styles/globals.css" />
      </Head>

      <div className="flex items-center justify-center bg-gradient-to-r from-black to-gray-950  h-screen">
        
        <h1 className="text-white text-center    font-serif font-bold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">WELCOME TO our BEAUTY APP  </h1> 
        
      </div>
      {/* Top products */} 

      <h1 className="text-4xl font-bold my-4 mx-2 ml-6 md:ml-24">
        Our Top Products
      </h1>

     

      
      <h1 className="text-4xl font-bold my-4 mx-2 ml-6 md:ml-24">Top-Deal</h1>
      <section className="w-full h-screen flex md:justify-center flex-nowrap ">
       
        
          {products.data.map((item) => {
            return (
              
              <Link  href={`/product/${item.attributes.slug}`}>

                <div className=" m-2"> 
                <div class=" h-">
                  <img
                    
                    src={item.attributes.img.data && item.attributes.img.data.attributes.url}
                    alt="Tall slender porcelain bottle with natural clay textured body and cork stopper."
                    className=""
                  />
                </div>
                <h3 class="mt-4 text-sm text-gray-700">
                  {item.attributes.title}
                </h3>
                <p class="mt-1 text-lg font-medium text-gray-900">
                ₹{item.attributes.price}
                </p>
                </div>
              </Link>
            )
          })}
        

      

       

        
      </section>

      <footer class="text-gray-600 body-font bottom-0">
        <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
          <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            
          
          </a>
          <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
            © 2024 faceScan —
            <a
              href="https://twitter.com/knyttneve"
              class="text-gray-600 ml-1"
              rel="noopener noreferrer"
              target="_blank"
            >
            
            </a>
          </p>
          <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
            <a class="text-gray-500">
              <svg
                fill="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="currentColor"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="0"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path
                  stroke="none"
                  d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
                ></path>
                <circle cx="4" cy="4" r="2" stroke="none"></circle>
              </svg>
            </a>
          </span>
        </div>
      </footer>
    </>
  );
};
export async function getServerSideProps(context) {
  let headers = {
    Authorization:
      "Bearer 264f9c48a0913b043ad9a26362fdb806087d935d1a6318de3c58fd56a94b5b1c9a5d003d092cdc6e65815ef26486b7e9388f23675387d952236a56112b759e5715e62672e17d0af96254533b8604962c166c8d87316ad796523f614eec61fe0b43777b84046965995648f61e3bd338f99c7607a1afa9845b3cbebdf29926d18d",
  };
  console.log("before");
  let a = await fetch("http://localhost:1337/api/Top-deals?populate=*", {
    headers: headers,
  });
  console.log("fatched");
  let products = await a.json();
  console.log(products);
  

  // console.log(products.data.attributes.thumbnail.data.attributes.name)
  return {
    props: { products: products },
  };
}
export default index;
