import Image from "next/image";
import image1 from "../public/images/image10.jpg";

import image2 from "../public/images/image11.jpg";
import image3 from "../public/images/image12.jpg";
import { HiOutlineShoppingBag } from "react-icons/hi";

import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";

import Head from "next/head";
import Middle from "@/components/Middle";
const index = ({ products , addToCart}) => {
  return (
    <>
      <Head>
        <title>Ecommerce-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="styles/globals.css" />
      </Head>

      <div className="flex items-center justify-center bg-gradient-to-r from-black to-gray-950  h-screen">
        
        <h1 className="text-white text-center    font-serif font-bold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">WELCOME TO our BEAUTY APP  </h1> 
        
      </div>
      {/* Top products */} 

      <h1 className="text-4xl font-bold my-4 mx-2 ml-6 md:ml-24">
        Our Top Products
      </h1>

      {/* <section className="w-full h-96 flex md:justify-center flex-nowrap overflow-x-auto ">
        {products.data.map((item) => {
          return (
            <div className="mx-8 md:mx-6">
              <div className="w-64 border-2 rounded-md ">
                {/* image Section */}
                {/* <div className="bg-slate-500 w-full h-58 ">
                  <img
                    src={
                      item.attributes.thumbnail.data &&
                      item.attributes.thumbnail.data.attributes.url
                    }
                  />
                </div> */}
                {/* about product */}
                {/* <div className="bg-slate-100">
                  
                  <div className="flex justify-between">
                    <div className="list-none m-1">
                      <li>{item.attributes.name}</li>
                      <li>₹{item.attributes.price}</li>
                    </div>
                    <div className="item-center justify-center">
                      <HiOutlineShoppingBag />
                    </div>
                  </div>
                </div>
              </div> */}
            {/* </div> */}
          {/* ); */}
        {/* })} */}
      {/* </section> */}

      
      <h1 className="text-4xl font-bold my-4 mx-2 ml-6 md:ml-24">Top-Deal</h1>
      <section className="w-full h-96 flex md:justify-center flex-nowrap overflow-x-auto ">
        <div className="mx-8 md:mx-6">
          <div className="w-64  border-2 rounded-md">
            <div className="">
              {/* image Section */}
              <div className="bg-slate-500 w-full h-64 ">image section</div>
              {/* about product */}
              <div className="bg-slate-100">
                <ul className="flex justify-between list-none">
                  <li className="list-none">rating</li>
                  <li className="list-none">colors</li>
                </ul>
                <div className="flex justify-between">
                  <div>
                    <li>product name</li>
                    <li>price</li>
                  </div>
                  <div>
                    <HiOutlineShoppingBag onClick={() => { addToCart("hello", 1, 120, 'foundation', 'XL', "Red") }}/>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mx-8 md:mx-6">
          <div className="w-64  border-2 rounded-md">
            <div className="">
              {/* image Section */}
              <div className="bg-slate-500 w-full h-64 ">image section</div>
              {/* about product */}
              <div className="bg-slate-100">
                <ul className="flex justify-between list-none">
                  <li className="list-none">rating</li>
                  <li className="list-none">colors</li>
                </ul>
                <div className="flex justify-between">
                  <div>
                    <li>product name</li>
                    <li>price</li>
                  </div>
                  <div>
                    <HiOutlineShoppingBag  />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mx-8 md:mx-6">
          <div className="w-64  border-2 rounded-md">
            <div className="">
              {/* image Section */}
              <div className="bg-slate-500 w-full h-64 ">image section</div>
              {/* about product */}
              <div className="bg-slate-100">
                <ul className="flex justify-between list-none">
                  <li className="list-none">rating</li>
                  <li className="list-none">colors</li>
                </ul>
                <div className="flex justify-between">
                  <div>
                    <li>product name</li>
                    <li>price</li>
                  </div>
                  <div>
                    <HiOutlineShoppingBag />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mx-8 md:mx-6">
          <div className="w-64  border-2 rounded-md">
            <div className="">
              {/* image Section */}
              <div className="bg-slate-500 w-full h-64 ">image section</div>
              {/* about product */}
              <div className="bg-slate-100">
                <ul className="flex justify-between list-none">
                  <li className="list-none">rating</li>
                  <li className="list-none">colors</li>
                </ul>
                <div className="flex justify-between">
                  <div>
                    <li>product name</li>
                    <li>price</li>
                  </div>
                  <div>
                    <HiOutlineShoppingBag />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer class="text-gray-600 body-font">
        <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
          <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            
          
          </a>
          <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
            © 2024 faceScan —
            <a
              href="https://twitter.com/knyttneve"
              class="text-gray-600 ml-1"
              rel="noopener noreferrer"
              target="_blank"
            >
            
            </a>
          </p>
          <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
            <a class="text-gray-500">
              <svg
                fill="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
              </svg>
            </a>
            <a class="ml-3 text-gray-500">
              <svg
                fill="currentColor"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="0"
                class="w-5 h-5"
                viewBox="0 0 24 24"
              >
                <path
                  stroke="none"
                  d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
                ></path>
                <circle cx="4" cy="4" r="2" stroke="none"></circle>
              </svg>
            </a>
          </span>
        </div>
      </footer>
    </>
  );
};
// export async function getServerSideProps(context) {
  // console.log(context.query.slug);
  // Fetch data from external API
  // let headers = {
  //   Authorization:
  //     "Bearer f2dc86acfb78c950fcbde0fa39547d40c9bcf401cba8e7220cf36d2a4e2acdcb6f77fe55ab5f0a49082553af4ea5fd40dceb57af5291e65377e5cf46ff157213fc5ecd20d806f3f72411840448f9f8ef8ac444466413cb32c390efd3773be47262df88a6f681e86d93fbcf0eca7eb8fd9ba5938a4e804165c5e5cf489374baa3",
  // };
  // console.log(context.query.slug);
  // let a = await fetch(
  //   ` http://localhost:1337/api/products?populate=*&[filters][categorys][slug][$eq]=top-products`,
  //   { headers: headers }
  // );
  // let products = await a.json();
  // console.log("first");
  // console.log(products);
  // Pass data to the page via props
  // return { props: { products: products } };
// }
export default index;
